# Generated by Django 3.0.13 on 2021-04-01 08:17

from django.db import migrations, models

import ensembl.production.djcore.models


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_dbcopy', '0005_targethostgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestjob',
            name='convert_innodb',
            field=models.BooleanField(default=False, verbose_name='Convert Innodb=>MyISAM'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='dry_run',
            field=models.BooleanField(default=False, verbose_name='Dry Run'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='email_list',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Notify Email(s)'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ended on'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted on'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='skip_optimize',
            field=models.BooleanField(default=False, verbose_name='Optimize on target'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_host',
            field=models.TextField(max_length=2048, verbose_name='Source Host'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_incl_db',
            field=ensembl.production.djcore.models.NullTextField(blank=True, max_length=2048, null=True,
                                                                 verbose_name='Included Db(s)'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_incl_tables',
            field=ensembl.production.djcore.models.NullTextField(blank=True, max_length=2048, null=True,
                                                                 verbose_name='Included Table(s)'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_skip_db',
            field=ensembl.production.djcore.models.NullTextField(blank=True, max_length=2048, null=True,
                                                                 verbose_name='Skipped Db(s)'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_skip_tables',
            field=ensembl.production.djcore.models.NullTextField(blank=True, max_length=2048, null=True,
                                                                 verbose_name='Skipped Table(s)'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Started on'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='tgt_db_name',
            field=ensembl.production.djcore.models.NullTextField(blank=True, max_length=2048, null=True,
                                                                 verbose_name='Target DbName(s)'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='tgt_host',
            field=models.TextField(max_length=2048, verbose_name='Target Host(s)'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='wipe_target',
            field=models.BooleanField(default=False, verbose_name='Wipe target'),
        ),
        migrations.AlterModelTable(
            name='group',
            table='host_group',
        ),
    ]
