# Generated by Django 3.0.13 on 2021-04-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0006_alter_helps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestjob',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='username',
            field=models.CharField(blank=True, db_column='user', max_length=64, null=True, verbose_name='Submitter'),
        ),
    ]
