# Generated by Django 3.0.13 on 2021-04-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0007_rename_field_user_to_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='server_host',
        ),
    ]
