# Generated by Django 3.2.2 on 2021-06-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0008_rename_host_table'),
    ]

    operations = [
        migrations.RenameModel('Group', 'HostGroup'),
        migrations.AlterModelOptions(
            name='targethostgroup',
            options={'verbose_name': 'Hosts Target HostGroup'},
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='username',
            field=models.CharField(db_column='user', max_length=64, null=True, verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='targethostgroup',
            name='target_group_name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Hosts HostGroup'),
        )
    ]
